- name: MacOS System and Software Management
  hosts: localhost
  connection: local
  # Change to true if running this file directly
  gather_facts: false

  tasks:
    - name: Ensure Homebrew and all formulae are updated/upgraded
      community.general.homebrew:
        update_homebrew: true
        upgrade_all: true

    - name: Install and update Applications via Homebrew Cask
      community.general.homebrew_cask:
        name: "{{ item }}"
        state: latest
        greedy: true
      loop:
        - stats
        - sublime-text
        - discord
        - firefox
